// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYpOgA_BuxSH29Ti57OKrXBqTkar2sjtE',
    appId: '1:762449541351:web:bfdc0b6454bffcf1318a42',
    messagingSenderId: '762449541351',
    projectId: 'coffeeshop-c9e89',
    authDomain: 'coffeeshop-c9e89.firebaseapp.com',
    storageBucket: 'coffeeshop-c9e89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPDFVSXX_V4sYyYRAtVk88GlVYtwE69JM',
    appId: '1:762449541351:android:6e9920682adf0239318a42',
    messagingSenderId: '762449541351',
    projectId: 'coffeeshop-c9e89',
    storageBucket: 'coffeeshop-c9e89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2QMDUaWHyG5-CwgmD0snK4gwO4waFecg',
    appId: '1:762449541351:ios:dc3b29ae28a31eab318a42',
    messagingSenderId: '762449541351',
    projectId: 'coffeeshop-c9e89',
    storageBucket: 'coffeeshop-c9e89.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2QMDUaWHyG5-CwgmD0snK4gwO4waFecg',
    appId: '1:762449541351:ios:dc3b29ae28a31eab318a42',
    messagingSenderId: '762449541351',
    projectId: 'coffeeshop-c9e89',
    storageBucket: 'coffeeshop-c9e89.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYpOgA_BuxSH29Ti57OKrXBqTkar2sjtE',
    appId: '1:762449541351:web:5312a687e2a48d18318a42',
    messagingSenderId: '762449541351',
    projectId: 'coffeeshop-c9e89',
    authDomain: 'coffeeshop-c9e89.firebaseapp.com',
    storageBucket: 'coffeeshop-c9e89.firebasestorage.app',
  );
}
